apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: workflowtrigger
    app.kubernetes.io/name: workflowtrigger
    app.kubernetes.io/part-of: atlas
  name: workflowtrigger
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: reposerver
    app.kubernetes.io/name: reposerver
    app.kubernetes.io/part-of: atlas
  name: reposerver
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: workfloworchestrator
    app.kubernetes.io/name: workfloworchestrator
    app.kubernetes.io/part-of: atlas
  name: workfloworchestrator
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: commanddelegator
    app.kubernetes.io/name: commanddelegator
    app.kubernetes.io/part-of: atlas
  name: commanddelegator
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: clientwrapper
    app.kubernetes.io/name: clientwrapper
    app.kubernetes.io/part-of: atlas
  name: clientwrapper
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: atlas
rules:
  - apiGroups: ["networking.istio.io", "apps", "", "batch", "core", "*"]
    resources: ["*"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: atlas-clusterrolebinding
subjects:
  - kind: ServiceAccount
    name: workflowtrigger
    namespace: atlas
  - kind: ServiceAccount
    name: reposerver
    namespace: atlas
  - kind: ServiceAccount
    name: workfloworchestrator
    namespace: atlas
  - kind: ServiceAccount
    name: commanddelegator
    namespace: atlas
  - kind: ServiceAccount
    name: clientwrapper
    namespace: atlas
roleRef:
  kind: ClusterRole
  name: atlas
  apiGroup: rbac.authorization.k8s.io
---
#Redis Service & Deployment
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.23.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: redisserver
  name: redisserver
spec:
  ports:
    - name: "6379"
      port: 6379
      targetPort: 6379
  selector:
    io.kompose.service: redisserver
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.23.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: redisserver
  name: redisserver
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: redisserver
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.23.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: redisserver
    spec:
      containers:
        - image: redis
          imagePullPolicy: IfNotPresent
          name: redisserver
          ports:
            - containerPort: 6379
          resources: {}
      restartPolicy: Always
status: {}
---
#WorkflowTrigger Service & Deployment
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.23.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: workflowtrigger
  name: workflowtrigger
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    io.kompose.service: workflowtrigger
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.23.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: workflowtrigger
    app.kubernetes.io/name: workflowtrigger
    app.kubernetes.io/part-of: atlas
  name: workflowtrigger
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: workflowtrigger
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.23.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: workflowtrigger
    spec:
      containers:
        - env:
            - name: KAFKA_BOOTSTRAP_SERVERS # docker-compose
              value: LOCALHOSTDYNAMICADDRESS:29092
#            - name: KAFKA_BOOTSTRAP_SERVERS # strimzi
#              value: atlas-kafka-0.atlas-kafka-brokers.kafka.svc.cluster.local:9092
            - name: ATLAS_DB_ADDRESS
              value: redisserver.atlas.svc.cluster.local:6379
            - name: REPO_SERVER_ENDPOINT
              value: http://reposerver.atlas.svc.cluster.local:8080
            - name: COMMAND_DELEGATOR_SERVER_ENDPOINT
              value: https://commanddelegator.atlas.svc.cluster.local:8080
          image: atlasworkflowtrigger
          imagePullPolicy: Never
          name: workflowtrigger
          ports:
            - containerPort: 8080
          resources: {}
      restartPolicy: Always
      serviceAccountName: workflowtrigger
status: {}
---
#PipelineRepoServer Service & Deployment
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.23.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: reposerver
  name: reposerver
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    io.kompose.service: reposerver
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.23.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: reposerver
    app.kubernetes.io/name: reposerver
    app.kubernetes.io/part-of: atlas
  name: reposerver
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: reposerver
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.23.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: reposerver
    spec:
      containers:
        - env:
            - name: REDIS_ENDPOINT
              value: redisserver.atlas.svc.cluster.local:6379
            - name: ORG_NAME
              value: org
          image: atlasreposerver
          imagePullPolicy: Never
          name: reposerver
          ports:
            - containerPort: 8080
          resources: {}
      restartPolicy: Always
      serviceAccountName: reposerver
status: {}
---
#WorkflowOrchestrator Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.23.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: workfloworchestrator
    app.kubernetes.io/name: workfloworchestrator
    app.kubernetes.io/part-of: atlas
  name: workfloworchestrator
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: workfloworchestrator
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.23.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: workfloworchestrator
    spec:
      containers:
        - env:
            - name: CLIENT_WRAPPER_ENDPOINT
              value: https://atlasclientwrapper.atlas.svc.cluster.local:9091
            - name: KAFKA_BOOTSTRAP_SERVERS # docker-compose
              value: LOCALHOSTDYNAMICADDRESS:29092
#            - name: KAFKA_BOOTSTRAP_SERVERS # strimzi
#              value: atlas-kafka-0.atlas-kafka-brokers.kafka.svc.cluster.local:9092
            - name: REDIS_ENDPOINT
              value: redisserver.atlas.svc.cluster.local:6379
            - name: REPO_SERVER_ENDPOINT
              value: http://reposerver.atlas.svc.cluster.local:8080
          image: atlasworkfloworchestrator
          imagePullPolicy: Never
          name: workfloworchestrator
          volumeMounts:
            - mountPath: /tls-cert
              name: certs
          resources: {}
      volumes:
        - name: certs
          hostPath:
            path: /tls-cert
      restartPolicy: Always
      serviceAccountName: workfloworchestrator
status: {}
---
#CommandDelegator Service & Deployment
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.23.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: commanddelegator
  name: commanddelegator
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    io.kompose.service: commanddelegator
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.23.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: commanddelegator
    app.kubernetes.io/name: commanddelegator
    app.kubernetes.io/part-of: atlas
  name: commanddelegator
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: commanddelegator
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.23.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: commanddelegator
    spec:
      containers:
        - env:
            - name: ATLAS_DB_ADDRESS
              value: redisserver.atlas.svc.cluster.local:6379
          image: atlascommanddelegator
          imagePullPolicy: Never
          name: commanddelegator
          ports:
            - containerPort: 8080
          resources: {}
      restartPolicy: Always
      serviceAccountName: commanddelegator
status: {}
---
# ClientWrapper Service & Deployment
apiVersion: v1
kind: Service
metadata:
  name: clientwrapper
  labels:
    app: clientwrapper
spec:
  ports:
    - port: 9091
      targetPort: 9091
  type: LoadBalancer
  selector:
    app: clientwrapper
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clientwrapper
  labels:
    app: clientwrapper
    app.kubernetes.io/name: clientwrapper
    app.kubernetes.io/part-of: atlas
spec:
  selector:
    matchLabels:
      app: clientwrapper
  replicas: 1
  template:
    metadata:
      labels:
        app: clientwrapper
    spec:
      serviceAccountName: clientwrapper
      containers:
        - env:
          - name: WORKFLOW_TRIGGER_SERVER_ADDR
            value: https://workflowtrigger.atlas.svc.cluster.local:8080
          - name: COMMAND_DELEGATOR_URL
            value: https://commanddelegator.atlas.svc.cluster.local:8080
          name: clientwrapper
          image: atlasclientwrapper
          imagePullPolicy: Never
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          ports:
            - containerPort: 8080
