version: "3.3"
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:6.2.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181

  kafka:
    image: confluentinc/cp-kafka:6.2.0
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
      - 9093:9093
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,SSL://kafka:9093, PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT, SSL:SSL, PLAINTEXT_HOST:PLAINTEXT
      KAFKA_SSL_KEYSTORE_FILENAME: 'certs/kafka.keystore.jks'
      KAFKA_SSL_KEYSTORE_CREDENTIALS: 'certs/kafka.keystore.credentials'
      KAFKA_SSL_KEY_CREDENTIALS: 'certs/kafka.key.credentials'
      KAFKA_SSL_TRUSTSTORE_FILENAME: 'certs/kafka.truststore.jks'
      KAFKA_SSL_TRUSTSTORE_CREDENTIALS: 'certs/kafka.truststore.credentials'
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - ./tls/certs/:/etc/kafka/secrets/certs

  workfloworchestrator:
    image: atlasworkfloworchestrator
    depends_on:
      - kafka
      - redisserver
      - workflowtrigger
      - reposerver
    links:
      - "kafka"
      - "redisserver"
      - "reposerver"
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - CLIENT_WRAPPER_ENDPOINT=http://host.docker.internal:9091
      - REPO_SERVER_ENDPOINT=http://reposerver:8081
      - REDIS_ENDPOINT=redisserver:6379

  workflowtrigger:
    image: atlasworkflowtrigger
    ports:
      - "8080:8080"
    depends_on:
      - kafka
      - redisserver
      - reposerver
    links:
      - "kafka"
      - "redisserver"
      - "reposerver"
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - REPO_SERVER_ENDPOINT=http://reposerver:8081
      - REDIS_ENDPOINT=redisserver:6379

  reposerver:
    image: atlasreposerver
    ports:
      - "8081:8081"
    depends_on:
      - redisserver
    links:
      - "redisserver"
    environment:
      - REDIS_ENDPOINT=redisserver:6379

  redisserver:
    image: redis
    ports:
      - "6379:6379"
