# there is a syntax error in verifyendpoints.sh
name: demo_pipeline_7
argo_version_lock: true
cluster_name: in-cluster
steps:
- name: deploy_to_dev
  application_path: testapp_dev.yml
  tests:
  - path: verifyendpoints.sh
    type: inject
    image: curlimages/curl:latest
    commands: [sh, -c, ./verifyendpoints.sh]
    before: false
    variables:
      SERVICE_INTERNAL_URL: testapp.dev.svc.cluster.local
- name: deploy_to_int
  application_path: testapp_int.yml
  tests:
  - path: verifyendpoints.sh
    type: inject
    image: curlimages/curl:latest
    commands: [sh, -c, ./verifyendpoints.sh]
    before: false
    variables:
      SERVICE_INTERNAL_URL: testapp.int.svc.cluster.local
  dependencies:
  - deploy_to_dev
