apiVersion: apps/v1
kind: Deployment
metadata:
  name: atlasverificationtool
  labels:
    app: atlasverificationtool
spec:
  selector:
    matchLabels:
      app: atlasverificationtool
  replicas: 1
  template:
    metadata:
      labels:
        app: atlasverificationtool
    spec:
      containers:
        - env:
            - name: CLIENT_WRAPPER_ENDPOINT
              value: http://atlasclientwrapper.default.svc.cluster.local:9091
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: LOCALHOSTDYNAMICADDRESS:29092
            - name: REDIS_ENDPOINT
              value: redisserver.default.svc.cluster.local:6379
            - name: REPO_SERVER_ENDPOINT
              value: http://reposerver.default.svc.cluster.local:8081
            - name: WORKFLOWTRIGGER_ENDPOINT
              value: http://workflowtrigger.default.svc.cluster.local:8080
            - name: KAFKA_GREENOPS_TOPIC
              value: greenops.eventing
            - name: KAFKA_VERIFICATIONTOOL_TOPIC
              value: verification.eventing
          image: atlasverificationtool
          imagePullPolicy: Never
          name: atlasverificationtool
          ports:
              - containerPort: 8080
          resources: {}
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: atlasverificationtool
  labels:
    app: atlasverificationtool
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: atlasverificationtool