---
apiVersion: v1
kind: Service
metadata:
  name: pipeline-repo-server
  labels:
    app: pipeline-repo-server
spec:
  ports:
    - port: 8080
      targetPort: 8080
  type: LoadBalancer
  selector:
    app: pipeline-repo-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pipeline-repo-server
  labels:
    app: pipeline-repo-server
spec:
  selector:
    matchLabels:
      app: pipeline-repo-server
  replicas: 1
  template:
    metadata:
      labels:
        app: pipeline-repo-server
    spec:
      containers:
        - name: repo-server
          image: atlas-repo-server
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          ports:
            - containerPort: 8080